name: 'Automated version bump'
description: 'Bump version following ShotGrid recommended way.'
inputs:
  tag:
    description: 'The tag of the app to be used to increment its version suffix where is v<major>.<minor>.<patch>.<version>'
    required: true
    default: 'v0.0.1'
  base-version:
    description: 'The base version of the app you forked from to compare against the tag.'
    required: false
    default: 'v0.0.1'
outputs:
  version:
    description: 'Version'
    value: ${{ steps.increment_version.outputs.version }}

runs:
  using: 'node16'
  main: 'dist/index.js'

# runs:
#   using: "composite"
#   steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
#       with:
#         # Required due to the way Git works, without it this action won't be able to find any or the correct tags
#         fetch-depth: '0'  
      
#     - name: 'Get Previous tag'
#       id: previoustag
#       uses: "Falcons-Creative-Group/github-action-get-previous-tag@v1"

#     - name: Print previous tag
#       run: echo "Previous tag was ${{ steps.previoustag.outputs.tag }}"
#       shell: bash

#     # If base-version is not provided, use the previous tag.
#     - name: Bump version
#       id: increment_version
#       run: |
#         base_version="${{ inputs.base-version }}"
#         if [ -z "$base_version" ]; then
#           base_version="${{ steps.previoustag.outputs.tag }}"
#         fi

#         if [ -z "$base_version" ]; then
#           base_version="v0.0.0"
#         fi

#         if [[ $base_version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
#           new_version="${base_version}.1"
#         else
#           local_change_version_number=$(echo "$base_version" | awk -F. '{print $NF}')
#           next_number=$((local_change_version_number + 1))
#           new_version=$(echo "$base_version" | sed "s/\.[0-9]*$/.${next_number}/")
#         fi
        
#         echo "version=$new_version" >> $GITHUB_OUTPUT
#         echo "New version is ${version}"
#       shell: bash